title = "Notre-Dame de Paris"
baseURL = "http://172.16.17.18"
languageCode = "en-us"
theme = "../../../ananke"
resourceDir = "../resources"

# defaultContentLanguage를 제거하여 기본 언어 설정을 하지 않습니다.
DefaultContentLanguage = "ko"

SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "Ananke"
weight = 1
contentDir = "content/en"
disablePath = true  # 언어 경로를 비활성화합니다

[languages.ko]
title = "Ananke ko"
weight = 2
contentDir = "content/ko"
disablePath = true  # 언어 경로를 비활성화합니다

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
background_color_class = "bg-black"
recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
