title = "Notre-Dame de Paris"
baseURL = "http://172.16.17.18"
languageCode = "en-us"
theme = "../../../ananke"
resourceDir = "../resources"

# 기본 언어 설정을 ko로 설정하려면 아래처럼 수정하세요.
defaultContentLanguage = "ko"

SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "PLURA Blog EN"
weight = 1
contentDir = "content/en"

[languages.ko]
title = "PLURA Blog KO"
weight = 2
contentDir = "content/ko"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
background_color_class = "bg-black"
recent_posts_number = 3
googleFonts = "https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap"  # 구글 폰트 링크 추가
customCSS = true  # custom.css를 사용할지 여부
#css_file = "/css/custom.css"  # custom.css 파일 경로 설정

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      autoHeadingID = true
      attribute = true
